#!/bin/bash

#echo -e "$(tput bold).aliases$(tput sgr0)"
#alias open='xdg-open'

alias jn=jupyter-notebook
alias g++='g++ -std=c++11'
alias clang='clang -std=c++11'
alias clean='rm -f *.{aux,log,out}(N)'
alias t='todo.sh'
alias gitacm='git add -A && git commit -m "Lazy update" && git push'
alias am='asciinema'

#export LS_COLORS=$(ls_colors_generator)
#run_ls() { ls-i --color=auto -w $(tput cols) "$@" }
#run_dir() { dir-i --color=auto -w $(tput cols) "$@" }
#run_vdir() { vdir-i --color=auto -w $(tput cols) "$@" }
#alias ls='run_ls'
#alias dir='run_dir'
#alias vdir='run_vdir'
