#!/bin/bash

#echo -e "$(tput bold).aliases$(tput sgr0)"
#alias open='xdg-open'

alias PS='poetry shell'
alias jn=jupyter-notebook
alias g++='g++ -std=c++11'
alias clang='clang -std=c++14'
alias clean='rm -f *.{aux,log,out,toc}(N)'
alias t='todo.sh'
# alias gitacm='git add -A && git commit -m "Lazy update" && git push'
alias am='asciinema'
alias tree='tree -C'

alias neovide='$HOME/.local/share/neovide --multiGrid --geometry=100x30'

gitacm() {
    msg=${1:-"Lazy commit"}
    git add -A && git commit -m "$msg" && git push
}

# Only for Windows with Linux subsystem
# <https://stackoverflow.com/a/53998402>
if uname -r | rg -q 'microsoft'; then
    alias open=explorer.exe
fi

alias pyenva='pyenv activate'
alias pyenvd='pyenv deactivate'

alias dcb='docker compose build'
alias dcu='docker compose up'
alias dcd='docker compose down'
alias dcr='docker compose restart'

alias myip='ip addr show dev eth0 | sed -nr "s/^\s*inet\s+([0-9]{1,3}(\.[0-9]{1,3}){3}).*$/\1/p"'

#export LS_COLORS=$(ls_colors_generator)
#run_ls() { ls-i --color=auto -w $(tput cols) "$@" }
#run_dir() { dir-i --color=auto -w $(tput cols) "$@" }
#run_vdir() { vdir-i --color=auto -w $(tput cols) "$@" }
#alias ls='run_ls'
#alias dir='run_dir'
#alias vdir='run_vdir'
