#!/bin/zsh

antigen use oh-my-zsh

antigen bundle vi-mode
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions

antigen theme https://github.com/denysdovhan/spaceship-zsh-theme spaceship

antigen apply
