#!/bin/bash

# Terminfo
#tic ~/.terminfo/xterm-256color-it.terminfo -o ~/.terminfo

# Vim plugins
#vim -u ~/.vimrc +PluginInstall +PluginClean +qa < /dev/tty "$@"

echo 'To change login shell to  Zsh: "chsh -s $(which zsh) $(whoami)"'
echo 'And lastly run ":PlugInstall" in vim/neovim to install the plugins'
