#!/bin/bash

# Setup Zsh
# (Plugin manager)
if [ ! -e ~/.antigen/antigen.zsh ]; then
  curl -fLo ~/.antigen/antigen.zsh --create-dirs \
    https://git.io/antigen
fi

# Setup vim
# (NOTE: outdated with nvim)
# (Directories)
# mkdir -p ~/.vim/{backup,swap,undo,bundle,snips}
# (Plugin manager)
# if [ ! -e ~/.vim/autoload/plug.vim ]; then
# 	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
# 	    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
# fi
